-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib a b sum
    | a > 4000000 = sum
    | even a = fib b (a+b) (sum+a)
    | otherwise = fib b (a+b) (sum)

main = do
    let f = fib 1 1 0
    print(f)